### ISSUE TITLE
Fails if link is defined in compose.yml

### ISSUE THREAD

**Issue by andrewsanchez** [fnichol/docker-ngrok#7]
https://github.com/fnichol/docker-ngrok/blob/338760aaf2a3af2deea64c8822db92cc10e404c9/ngrok_discover#L13-L18

```
version: "3.7"
services:

  listener:
    image: listener
    build:
      context: ./listener
    ports:
      - "5000:80"
    volumes:
      - "/Users/asanchez122/Projects/webhook-listener/data:/app/data"

  tunnel:
    image: fnichol/ngrok
    ports:
      - "3270:4040"
    links:
      - "listener:http"
```

Adding this to compose.yml fixed the issue:
```
    environment:
      HTTP_PORT: 4040
```
